version: '3'
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000

    ports:
     - "8000:8000"
    
    volumes:
      - .:/code
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'docker'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'admin'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'Admin@123'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3360:3306'
    # expose:
    #   # Opens port 3306 on the container
    #   - '3360'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
# Names our volume
volumes:
  my-db:
   

   
